### ISSUE TITLE
Add Docker container for Demo Building

### ISSUE THREAD

**Issue by Jochen-Kall** [elisa-tech/wg-automotive#13]
Add Sudips Container and Usage instructions to the workgroup repo
https://lists.elisa.tech/g/automotive/message/346
Add link from the meta-elisa build instructions, to avoid polluting the meta-elisa layer repo

**Comment by pahmann** [comment]
Done. Result can be found here: https://github.com/elisa-tech/wg-automotive/tree/master/Docker_container
