### ISSUE TITLE
Add section to onboarding documents on DCO and commit signing

### ISSUE THREAD

**Issue by Jochen-Kall** [elisa-tech/wg-automotive#16]
* setting up git, using --signoff when committing
* DCO checks at github
* setting up tig
* setting up WSL for windows users
to have the linux tooling availlable for Windows users

**Comment by pahmann** [comment]
This is covered in: https://github.com/elisa-tech/wg-automotive#workflow and https://github.com/elisa-tech/wg-automotive#git-newbie-section
