### ISSUE TITLE
Transition the initial Telltale use case safety concept from google docs to a github page

### ISSUE THREAD

**Issue by Jochen-Kall** [elisa-tech/wg-automotive#2]
https://drive.google.com/file/d/1GQ9FwFEJz9hLjhK_xTEi2DVBmgU2DBnX/view?usp=sharing

**Comment by pahmann** [comment]
Text part of this issue is addressed in: https://github.com/elisa-tech/wg-automotive/pull/5

**Comment by pahmann** [comment]
#5 was the initial commit for the update
#6 is the second part to include images from google doc.
pending is to transfer the images to plant uml

**Comment by pahmann** [comment]
Continuation of PlantUml is in discussion within working group as traceability will become complicated across multiple puml files. Waiting for conclusion or merge of @Jochen-Kall's work.

**Comment by pahmann** [comment]
Useful starting point may be STPA analysis: https://github.com/elisa-tech/wg-automotive/tree/master/Cluster_Display_Use_Case_v2/stpa
