### ISSUE TITLE
build AGL needlefish cluster demo

### ISSUE THREAD

**Issue by pahmann** [elisa-tech/wg-automotive#33]
The original demo used in the ELISA Automotive WG was built on AGL koi. Current release is needlefish. For the overall analysis it is not mandatory to have the migration from koi to needlefish. The main reason to start this task is to migrate the cluster demo as enhanced from ELISA.
The concrete step for this task is to build a qemu image with the AGL cluster demo enabled and QT as rendering backend.

Follow up tasks (and out of scope of this task) could be:
- Migrate [meta-elisa](https://github.com/elisa-tech/meta-elisa) from koi to needlefish
- Bring the demo from QT to Flutter
- create a SBOM for the needlefish based demo

It is a good first issue, as it can be handled standalone. The hardware requirements are important to handle, as you will require at least 16GB RAM and 100GB free disk space. Building a yocto image always require time.

**Comment by pahmann** [comment]
![Image](https://user-images.githubusercontent.com/2428012/202006976-48f605dc-5415-4df3-a7aa-f3d7d3b24189.png)

Demo started with needlefish. Following items are pending:
- Enable [vcan](https://github.com/elisa-tech/meta-elisa/tree/master/meta-elisa-demo/recipes-elisa/vcan) again 
- Apply ["Add new icon patch"](https://github.com/elisa-tech/meta-elisa/blob/master/meta-elisa-demo/recipes-elisa/cluster-safety-demo/cluster-dashboard_git.bbappend) again (as patch did not apply with my build)

**Comment by sudipm-mukherjee** [comment]
Just an update: The patch for the display has been done, and I have verified by manually changing the value that it displayes `danger`.                 
Looking at the CAN part now, as the CAN implementation in AGL is now via an abstraction layer based on `kuksa`.

**Comment by pahmann** [comment]
Sudip provide a patch for the Danger icon in the cluster demo. Rendering is also properly now. Missing part is the kuksa part for CAN (formerly vcan)

![image](https://user-images.githubusercontent.com/2428012/203097666-fd65b190-a74d-4081-bb0c-61b7abd1eafa.png)

**Comment by sudipm-mukherjee** [comment]
PR now created for this update.
`Bring the demo from QT to Flutter` was not necessary, as AGL still has the QT based demo that we had been using.

**Comment by pahmann** [comment]
Build is reproduced by @sudipm-mukherjee and @pahmann and now also is added to CI.
The related PR for needlefish can be found here: https://github.com/elisa-tech/meta-elisa/pull/28
