### ISSUE TITLE
Expand demo app sequence diagram to flesh out safet_signal_source functionality

### ISSUE THREAD

**Issue by Jochen-Kall** [elisa-tech/wg-automotive#4]
https://github.com/Jochen-Kall/wg-automotive/blob/master/Safety_demo_analysis/Diagrams_onlineview.md

**Comment by pahmann** [comment]
This moved into AGL Cluster demo use case analysis.
https://github.com/elisa-tech/wg-automotive/blob/master/AGL_cluster_demo_use_case/Safety-analysis/Diagrams_onlineview.md
